# Generated by Django 2.1.3 on 2019-04-07 14:32

import KrillApp.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image', models.ImageField(unique=True, upload_to=KrillApp.models.user_directory_path)),
                ('file_name', models.TextField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Krill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('maturity', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('image_annotation', models.TextField(default='')),
                ('image_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KrillApp.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='trip_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KrillApp.Trip'),
        ),
    ]
