# Generated by Django 2.1.3 on 2019-01-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KrillApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.AlterField(
            model_name='image',
            name='user_name',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
        ),
    ]
