# Generated by Django 2.1.3 on 2019-04-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KrillApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_annotations',
            field=models.TextField(default=''),
        ),
    ]
