# Generated by Django 2.1.3 on 2019-01-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KrillApp', '0002_auto_20190123_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='user_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
