# Generated by Django 2.1.3 on 2019-06-05 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KrillApp', '0002_image_image_annotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='krill',
            name='unique_krill_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
