# Generated by Django 2.1.3 on 2019-03-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KrillApp', '0003_auto_20190123_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_annotations',
            field=models.TextField(default=''),
        ),
    ]
