# Generated by Django 2.1.3 on 2019-06-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KrillApp', '0004_auto_20190607_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krill',
            name='length',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
