# Generated by Django 2.1.5 on 2019-06-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KrillApp', '0005_auto_20190607_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='krill',
            name='id',
        ),
        migrations.AddField(
            model_name='krill',
            name='height',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='krill',
            name='width',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='krill',
            name='x',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='krill',
            name='unique_krill_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
