# Generated by Django 2.1.5 on 2019-06-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KrillApp', '0006_auto_20190610_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='krill',
            name='y',
            field=models.CharField(default='', max_length=50),
        ),
    ]
